### ISSUE TITLE
Valores mínimos y máximos están al revés en `best_logistic_model_parameters_laal_ig.json`

### ISSUE THREAD

**Issue by evaristor** [IslasGECI/dimorfismo#11]
Abajo se puede ver que el valor mínimo del alto del pico es más grande que el valor máximo y los mismo con el tarso:

```
{
  "parametrosNormalizacion": {
    "valorMinimo": {
      "longitudCraneo": [3.7037],
      "altoPico": [165.58],
      "longitudPico": [29.67],
      "tarso": [101.78]
    },
    "valorMaximo": {
      "longitudCraneo": [83.18],
      "altoPico": [46.5],
      "longitudPico": [193.22],
      "tarso": [35.44]
    }
  },
  "parametrosModelo": [
    {
      "Variables": "(Intercept)",
      "Estimate": -18.948,
      "_row": "(Intercept)"
    },
    {
      "Variables": "longitudCraneo",
      "Estimate": 6.576,
      "_row": "longitudCraneo"
    },
    {
      "Variables": "altoPico",
      "Estimate": 8.816,
      "_row": "altoPico"
    },
    {
      "Variables": "longitudPico",
      "Estimate": 7.172,
      "_row": "longitudPico"
    },
    {
      "Variables": "tarso",
      "Estimate": 5.726,
      "_row": "tarso"
    }
  ]
}
```

**Comment by andrea-sanchez** [comment]
Para poder atender este _issue_, se planea crear una prueba que identifique que los valores mínimos sean menores a los máximos. La prueba fallará y después se refactorizarán los archivos de código hasta pasar la prueba.

**Comment by nepito** [comment]
@andrea-sanchez por favor me señalas cuál es el archivo que genera este archivo. Creo que agarramos valores ya generados y los ponenmos un los lugares inadecuados. Creo que:
> Tal vez estén relacionados con el hecho de que los valores altura pico (mínimo = 166.6) y longitud pico (máximo = 193.22) son lo valores mínimo y máximos de longitud craneo de la tabla anterior. Lo mismo ocurre con longitud pico (mínimo = 28.85) y Tarso (máximo = 35.47) y los valores de altura pico de la tabla anterior. Me parece mucha casualidad que los valores se repitan en variables distintas.

**Comment by andrea-sanchez** [comment]
Este _issue_ fue resuelto en el [`release #15 `](https://github.com/IslasGECI/dimorfismo/pull/15) con la [consignación 5d15ad8](https://github.com/IslasGECI/dimorfismo/pull/15/commits/487493ef16da76e7a0ca301d8a0ab793a35611c7) y también, dentro del mismo `release #15`, se encuentra la [prueba que acredita](https://github.com/IslasGECI/dimorfismo/pull/15/commits/487493ef16da76e7a0ca301d8a0ab793a35611c7) las modificaciones en el código.

**Comment by evaristor** [comment]
Gracias, @andrea-sanchez. Entonces esperaremos a que termine #15 para marcar como resuleto este _issue_

**Comment by evaristor** [comment]
Parece que todavía está en _spanglish_
```
  "normalization_parameters": {
    "minimum_value": {
      "longitud_craneo": [11.1111],
      "altura_pico": [166.8],
      "longitud_pico": [28.85],
      "tarso": [100.81]
    }
```
