### ISSUE TITLE
Mi primera clase

### ISSUE THREAD

**Issue by nepito** [IslasGECI/dimorfismo#16]
Programa la primera clase en R6. [Aquí](https://adv-r.hadley.nz/r6.html#r6-classes) podrás encontrar algo similar a la prueba y al inicio del capítulo verás cómo definir las clases.

**Comment by evaristor** [comment]
@nepito @andrea-sanchez : Por favor podríamos mover este ejemplo didáctico al repo [`ejemplo_para_andrea`](https://github.com/IslasGECI/ejemplo_para_andrea)?

**Comment by evaristor** [comment]
Moví este _issue_ al repo **ejemplo_para_andrea** [#6](https://github.com/IslasGECI/ejemplo_para_andrea/issues/6)
