### ISSUE TITLE
Agregar "prueba máxima" 

### ISSUE THREAD

**Issue by nepito** [IslasGECI/dimorfismo#17]
Agrega el reporte al _phony_ `all` para poder refactorizar sin miedo.

**Comment by andrea-sanchez** [comment]
La _**prueba máxima**_ entró a la `develop` al cerrarse [el PR #15 ](https://github.com/IslasGECI/dimorfismo/pull/15) bajo la consignación [Agrega instrucción provisional en ALL del Makefile 744747](https://github.com/IslasGECI/dimorfismo/pull/15/commits/744747e8cfb2be7323337bf754499f7022add5c1)
