### ISSUE TITLE
Mutaciones

### ISSUE THREAD

**Issue by nepito** [IslasGECI/dimorfismo#23]
- [ ] Sobrevivó un mutante Aritmetic Operador del archivo `03_predict_sex.R` en la linea 52:
+`final_prob <- ifelse(sum(males) * length(males) * 100 == "100", 1, 0)`
-`final_prob <- ifelse(sum(males) / length(males) * 100 == "100", 1, 0)`

**Comment by evaristor** [comment]
@nepito ¿En que rama probaste esto? ¿Fue en la de #22?

**Comment by andrea-sanchez** [comment]
> @nepito ¿En que rama probaste esto? ¿Fue en la de #22?

@evaristor sip, dentro del `feature/03_tests`
