### ISSUE TITLE
Sugerencia pendiente en 01_create_parameter_logistic_model_LAAL.R

### ISSUE THREAD

**Issue by andrea-sanchez** [IslasGECI/dimorfismo#27]
[Sugerecia](https://github.com/IslasGECI/dimorfismo/pull/26#discussion_r508891934) de @nepito en el [**Pull Request** : Pruebas caja negra en 'calculator_roc_class.R'](https://github.com/IslasGECI/dimorfismo/pull/26)

> Este archivo es de 243 líneas y me gustaría que ahora lo tratáramos de hacer de unas 50 líneas, así que te iré proponiendo unos poquitos de cambios. Por ejemplo me gustaría hacer tres funciones una (la tercera a la que llamaré `fit_step_regration`) implementará las otras dos (a las que llamaré `fit_null_model` y `fit_completed_model`). 
> 
> Así me imagino que podríamos cambiar las [líneas 106-113](https://github.com/IslasGECI/dimorfismo/pull/26/files?file-filters%5B%5D=.R#diff-49847d3e5df40631cdfa2dcac0bda849931490a742ba4ce5472e26f26fdb26a3R106-R113) que ahora se ve así:
> ```
> step_regression <- step(null_regression,
>     scope = list(
>       lower = null_regression,
>       upper = all_regression
>     ),
>     direction = "both",
>     trace = 0
>   )
> ```
> por algo más o menos así:
> ```
> step_regression <- fit_step_regression(normalized_data)
> ```
> y esa "hipotética" función me la imagino con la siguiente forma:
> ```
> fit_step_regression <- function(normalized_data) {
>   null_regression <- fit_null_regression(normalized_data)
>   completed_regression <- fit_completed_regression(normalized_data)
>   step_regression <- make_step_regression(null_regression, completed_regression)
> }
> ```
>  Y por último a la función `make_step_regression` con la forma:
> ```
> make_step_regression <- function(null_regression, all_regression){
> step(null_regression,
>     scope = list(
>       lower = null_regression,
>       upper = all_regression
>     ),
>     direction = "both",
>     trace = 0
>   )
> }
> ```
> 
> ¿Qué te parece el borrador de propuesta? Claro que estaría ideal que esas funciones pudieran tener sus respectivas pruebas, pero eso solo es un ideal.
> 
> Por favor implementa la fucnión `fit_step_regression`.

**Comment by evaristor** [comment]
@andrea-sanchez : ¿Crearás un nuevo PR para atender esta sugerencua?

**Comment by andrea-sanchez** [comment]
@evaristor  Así es! En cuanto termine con el[ PR#30](https://github.com/IslasGECI/dimorfismo/pull/30) la siguiente tarea es refactorizar el archivo `01_create_parameter_logistic_model_LAAL.R`, lo cual involucra este el issue #27 y el issue #29 

> @andrea-sanchez : ¿Crearás un nuevo PR para atender esta sugerencua?

**Comment by AlejandroPad** [comment]
Ya refactorizamos las funciones mencionadas, dichas se encuentran en `~/R/regretion_to_data_frame_coefficients_function.R` por lo que podemos seguir con lo de crear la función mencionada
