### ISSUE TITLE
Variable no utilizada en 01_create_parameter_logistic_model_LAAL.R

### ISSUE THREAD

**Issue by andrea-sanchez** [IslasGECI/dimorfismo#29]
En el archivo `01_create_parameter_logistic_model_LAAL.R` no se utiliza la variable `n_individuals <- length(unique(averaged_data$id_darvic))` después de declararse en la linea 78.

**Comment by evaristor** [comment]
Y si la borras pasan la pruebas?

**Comment by andrea-sanchez** [comment]
> Y si la borras pasan la pruebas?

@evaristor sí, señor! :cowboy_hat_face: 
Hice el este _issue_ con la idea de agregar otras variables no utilizadas en el script `01_create_parameter_logistic_model_LAAL.R`

**Comment by evaristor** [comment]
Si el código está cubierto con pruebas resistente a mutaciones, entonces bórra todas las variables con los ojos cerrados :see_no_evil:

**Comment by evaristor** [comment]
¿Qué tanto confías en las pruebas?

**Comment by andrea-sanchez** [comment]
> ¿Qué tanto confías en las pruebas?

@evaristor está muy presente el suspenso detrás de esta pregunta jajaja Me atrevería a decir, que confío plenamente en ellas 😬

**Comment by evaristor** [comment]
@andrea-sanchez : ¿Finalmente qué pasó aquí? ¿Borraste `n_individuals`?

**Comment by andrea-sanchez** [comment]
@evaristor  Así es! En cuanto termine con el[ PR#30](https://github.com/IslasGECI/dimorfismo/pull/30) la siguiente tarea es refactorizar el archivo `01_create_parameter_logistic_model_LAAL.R`, lo cual involucra este el issue #29 y el issue #27  

> @andrea-sanchez : ¿Finalmente qué pasó aquí? ¿Borraste `n_individuals`?

**Comment by AlejandroPad** [comment]
En el [PR #43](https://github.com/IslasGECI/dimorfismo/pull/43) Se elimina la variable no utilizada.
