### ISSUE TITLE
✨♻️ ⚡️ Crear clase model_table

### ISSUE THREAD

**Issue by andrea-sanchez** [IslasGECI/dimorfismo#32]
Durante la refactorización ♻️ del  archivo` 01_create_parameter_logistic_model_LAAL.R` podemos crear la clase `model_table` donde sea posible encapsular en instrucciones de la siguiente manera: 

Declarar la clase con base a las siguientes líneas: 

![issue02-1](https://user-images.githubusercontent.com/60370110/102406688-ce64e200-3f9f-11eb-909c-1cde3cfb0cf1.png)
**Sidenote**: Hay algo extraño en las líneas 43-48, revisar :eyes: bien

Un método privado `get_step_coeficients` donde se generen las asignaciones: 
![issue02-2](https://user-images.githubusercontent.com/60370110/102406846-0a984280-3fa0-11eb-9c19-2bbf587cb2bf.png)

**Comment by andrea-sanchez** [comment]
Podemos crear un método que permita encapsular las siguientes instrucciones:
![issue02-3](https://user-images.githubusercontent.com/60370110/102407396-eab54e80-3fa0-11eb-96e2-4b4dfd59df6e.png)
Además, crear un método privado que donde, al introducir el string "example" regrese el vector c("example_intercept", "example_longitud_craneo", "example_alto_pico", "example_tarso", "example_ancho_craneo") con la finalidad de eliminar las líneas 184, 189 y 195.

**Comment by andrea-sanchez** [comment]
Agregar al método anterior, 

![issue02-4](https://user-images.githubusercontent.com/60370110/102408837-0883b300-3fa3-11eb-8d12-9242d6212ec3.png)


Además, crear un método privado que donde, al introducir el _string_ `example` regrese el vector` c("example_longitud_craneo", "example_alto_pico", "example_tarso", "example_ancho_craneo") `con la finalidad de modificar las líneas 203 y 209.

**Comment by andrea-sanchez** [comment]
Al concluir la clase debe regresar lo siguiente:

![issue02-5](https://user-images.githubusercontent.com/60370110/102409252-9364ad80-3fa3-11eb-917a-530e5b4ea8ae.png)

**Comment by AlejandroPad** [comment]
@nepito Podríamos trabajar el siguiente PR en la anterior refactorización
