### ISSUE TITLE
⚡️ Nuevo método privado en clase calculator_roc

### ISSUE THREAD

**Issue by andrea-sanchez** [IslasGECI/dimorfismo#33]
Dentro de la clase `calculator_roc` en el método privado `roc_calculate` podemos crear un nuevo método privado `get_confusion_matrix` donde encapsulemos las líneas 79-85

![issue03](https://user-images.githubusercontent.com/60370110/102409629-3f0dfd80-3fa4-11eb-8889-39f090a66ae0.png)

**Comment by AlejandroPad** [comment]
Me parece correcto crear un método privado, así poder encapsular más lineas.
